[package]
name = "tuiflow-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"]}
tuiflow-model = { path = "../tuiflow-model" }
crossterm = "0.29.0"
