[package]
name = "tuiflow-model"
version = "0.1.0"
edition = "2021"

[dependencies]
mockall = "0.13.1"
serde = { version = "1.0.219", features = ["derive"] }
regex = "1.11.1"
tuiflow-model-contracts = { path = "../tuiflow-model-contracts" }