component Workflow {
    [StateMachine] as StateMachine
    [WorkflowFactory] as WorkflowFactory
    StateMachine -r- WorkflowFactory
}

() "Terminal" as Terminal
Terminal -d- StateMachine

() "Builder" as Builder
Builder -d- WorkflowFactory

[UI] as UI
UI -d-( Terminal

[Loader] as Loader
Loader -d-( Builder

UI -r- Loader